module.exports = {
  logoCss: {
    width: 400,
    height: 100,
    resizeMode: "contain",
    backgroundColor: "#153455",
    marginBottom: 50,
  },
  inputView: {
    height: 50,
    borderColor: "#c9c9c9",
    backgroundColor: "#ccc",
    borderWidth: 1,
    marginBottom: 20,
    paddingHorizontal: 10,
    borderRadius: 10,
    justifyContent: "center",
    padding: 20,
    width: 300,
  },
  inputText: {
    height: 50,
    color: "#000000",
    borderColor: "#333333",
  },
  loginButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "#153455",
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
    marginBottom: 10,
    width: 100,
  },
  loginButtonSkip: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "#153455",
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
    marginBottom: 10,
    width: "40%",
  },
  loginButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
  },
};
